"""rename stripe columns to lemonsqueezy in organizations

Revision ID: 57d92ffe4b8e
Revises: 75b465a78464
Create Date: 2026-07-18 01:22:45.580237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d92ffe4b8e'
down_revision: Union[str, None] = '75b465a78464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('lemonsqueezy_customer_id', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('lemonsqueezy_subscription_id', sa.String(length=255), nullable=True))
    op.drop_constraint('organizations_stripe_customer_id_key', 'organizations', type_='unique')
    op.drop_constraint('organizations_stripe_subscription_id_key', 'organizations', type_='unique')
    op.create_unique_constraint(None, 'organizations', ['lemonsqueezy_subscription_id'])
    op.create_unique_constraint(None, 'organizations', ['lemonsqueezy_customer_id'])
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_unique_constraint('organizations_stripe_subscription_id_key', 'organizations', ['stripe_subscription_id'])
    op.create_unique_constraint('organizations_stripe_customer_id_key', 'organizations', ['stripe_customer_id'])
    op.drop_column('organizations', 'lemonsqueezy_subscription_id')
    op.drop_column('organizations', 'lemonsqueezy_customer_id')
    # ### end Alembic commands ###
